module.exports = function seed(db) {
  // Categories - đúng theo screenshot
  const cats = [
    { name: 'Máy lạnh treo tường', slug: 'may-lanh-treo-tuong', icon: '❄️', image: '', sort_order: 1 },
    { name: 'Máy lạnh thương mại', slug: 'may-lanh-thuong-mai', icon: '🏢', image: '', sort_order: 2 },
    { name: 'Máy giặt', slug: 'may-giat', icon: '🫧', image: '', sort_order: 3 },
    { name: 'Máy giặt kết hợp sấy', slug: 'may-giat-say', icon: '🌀', image: '', sort_order: 4 },
    { name: 'Máy lọc không khí', slug: 'may-loc-khong-khi', icon: '💨', image: '', sort_order: 5 },
    { name: 'Máy lọc nước', slug: 'may-loc-nuoc', icon: '💧', image: '', sort_order: 6 },
    { name: 'Máy sấy', slug: 'may-say', icon: '🌬️', image: '', sort_order: 7 },
    { name: 'Tivi', slug: 'tivi', icon: '📺', image: '', sort_order: 8 },
    { name: 'Tủ lạnh', slug: 'tu-lanh', icon: '🧊', image: '', sort_order: 9 },
    { name: 'Máy rửa chén', slug: 'may-rua-chen', icon: '🍽️', image: '', sort_order: 10 },
    { name: 'Bếp từ', slug: 'bep-tu', icon: '🍳', image: '', sort_order: 11 },
    { name: 'Máy hút mùi', slug: 'may-hut-mui', icon: '🔄', image: '', sort_order: 12 },
    { name: 'Linh kiện – Phụ kiện', slug: 'linh-kien-phu-kien', icon: '🔩', image: '', sort_order: 13 },
    { name: 'Lò nướng – Lò vi sóng', slug: 'lo-nuong-lo-vi-song', icon: '🥘', image: '', sort_order: 14 },
    { name: 'Gia dụng khác', slug: 'gia-dung-khac', icon: '🏠', image: '', sort_order: 15 },
  ];
  const insertCat = db.prepare('INSERT INTO categories (name,slug,icon,image,sort_order) VALUES (?,?,?,?,?)');
  cats.forEach(c => insertCat.run(c.name, c.slug, c.icon, c.image, c.sort_order));

  // Products
  const products = [
    // Máy lạnh treo tường (cat 1)
    { name: 'Daikin Inverter FTKB25WAVMV 9000BTU', slug: 'daikin-ftkb25wavmv-9000btu', category_id: 1, brand: 'Daikin', model: 'FTKB25WAVMV', price: 8250000, original_price: 9500000, description: 'Máy lạnh Daikin Inverter tiết kiệm điện, làm lạnh nhanh, lọc không khí hiệu quả.', specs: JSON.stringify({ 'Công suất': '9.000 BTU', 'Công nghệ': 'Inverter', 'Diện tích': '10-15 m²', 'Gas': 'R32', 'Điện năng tiêu thụ': '0.78 kW/h' }), image: 'https://placehold.co/400x300/e8f4fd/1a5eb8?text=Daikin+9000BTU', is_featured: 1, is_sale: 1, stock: 15 },
    { name: 'Daikin Inverter FTKB35WAVMV 12000BTU', slug: 'daikin-ftkb35wavmv-12000btu', category_id: 1, brand: 'Daikin', model: 'FTKB35WAVMV', price: 10200000, original_price: 11800000, description: 'Máy lạnh Daikin 12000BTU Inverter, phù hợp phòng 15-20m².', specs: JSON.stringify({ 'Công suất': '12.000 BTU', 'Công nghệ': 'Inverter', 'Diện tích': '15-20 m²', 'Gas': 'R32', 'Điện năng tiêu thụ': '1.05 kW/h' }), image: 'https://placehold.co/400x300/e8f4fd/1a5eb8?text=Daikin+12000BTU', is_featured: 1, is_sale: 1, stock: 12 },
    { name: 'Panasonic Inverter CU/CS-PU9XKH-8 9000BTU', slug: 'panasonic-pu9xkh-9000btu', category_id: 1, brand: 'Panasonic', model: 'CS-PU9XKH-8', price: 7900000, original_price: 9200000, description: 'Máy lạnh Panasonic Inverter, công nghệ Econavi thông minh, kháng khuẩn Nano.', specs: JSON.stringify({ 'Công suất': '9.000 BTU', 'Công nghệ': 'Inverter + Econavi', 'Diện tích': '10-15 m²', 'Gas': 'R32' }), image: 'https://placehold.co/400x300/e8f4fd/1a5eb8?text=Panasonic+9000BTU', is_featured: 1, is_sale: 1, stock: 10 },
    { name: 'Panasonic Inverter CU/CS-PU12XKH-8 12000BTU', slug: 'panasonic-pu12xkh-12000btu', category_id: 1, brand: 'Panasonic', model: 'CS-PU12XKH-8', price: 9800000, original_price: 11000000, description: 'Máy lạnh Panasonic 12000BTU Inverter, lọc bụi mịn PM2.5.', specs: JSON.stringify({ 'Công suất': '12.000 BTU', 'Công nghệ': 'Inverter', 'Diện tích': '15-20 m²', 'Gas': 'R32' }), image: 'https://placehold.co/400x300/e8f4fd/1a5eb8?text=Panasonic+12000BTU', is_featured: 0, is_sale: 0, stock: 8 },
    { name: 'Mitsubishi Heavy Inverter SRK/SRC10CSS 9000BTU', slug: 'mitsubishi-heavy-srk10css-9000btu', category_id: 1, brand: 'Mitsubishi Heavy', model: 'SRK/SRC10CSS', price: 8000000, original_price: 9500000, description: 'Máy lạnh Mitsubishi Heavy Inverter 1HP, tiết kiệm điện, bền bỉ.', specs: JSON.stringify({ 'Công suất': '9.000 BTU', 'Công nghệ': 'Inverter', 'Diện tích': '10-15 m²', 'Gas': 'R32' }), image: 'https://placehold.co/400x300/e8f4fd/1a5eb8?text=Mitsubishi+Heavy+1HP', is_featured: 1, is_sale: 1, stock: 6 },
    { name: 'LG Inverter V10WIN1 9000BTU', slug: 'lg-v10win1-9000btu', category_id: 1, brand: 'LG', model: 'V10WIN1', price: 7500000, original_price: 8800000, description: 'Máy lạnh LG Dual Inverter tiết kiệm điện đến 70%, làm lạnh cực nhanh.', specs: JSON.stringify({ 'Công suất': '9.000 BTU', 'Công nghệ': 'Dual Inverter', 'Diện tích': '10-15 m²', 'Gas': 'R32' }), image: 'https://placehold.co/400x300/e8f4fd/1a5eb8?text=LG+9000BTU', is_featured: 1, is_sale: 1, stock: 14 },
    { name: 'Samsung Wind-Free Inverter 9000BTU', slug: 'samsung-ar09tyhqa-9000btu', category_id: 1, brand: 'Samsung', model: 'AR09TYHQASINSVN', price: 6800000, original_price: 8000000, description: 'Máy lạnh Samsung Wind-Free Inverter, làm lạnh không gió trực tiếp.', specs: JSON.stringify({ 'Công suất': '9.000 BTU', 'Công nghệ': 'Wind-Free Inverter', 'Diện tích': '10-15 m²', 'Gas': 'R32' }), image: 'https://placehold.co/400x300/e8f4fd/1a5eb8?text=Samsung+9000BTU', is_featured: 1, is_sale: 1, stock: 20 },
    { name: 'Casper Inverter HC-09TL32 9000BTU', slug: 'casper-hc09tl32-9000btu', category_id: 1, brand: 'Casper', model: 'HC-09TL32', price: 4900000, original_price: 5800000, description: 'Máy lạnh Casper Inverter 1HP giá tốt, tiết kiệm điện.', specs: JSON.stringify({ 'Công suất': '9.000 BTU', 'Công nghệ': 'Inverter', 'Diện tích': '10-15 m²', 'Gas': 'R32' }), image: 'https://placehold.co/400x300/e8f4fd/1a5eb8?text=Casper+9000BTU', is_featured: 0, is_sale: 1, stock: 18 },
    { name: 'Aqua Inverter AQA-RV10QC 9000BTU', slug: 'aqua-rv10qc-9000btu', category_id: 1, brand: 'Aqua', model: 'AQA-RV10QC', price: 5000000, original_price: 6200000, description: 'Máy lạnh Aqua Inverter 1HP, tiết kiệm điện, thiết kế hiện đại.', specs: JSON.stringify({ 'Công suất': '9.000 BTU', 'Công nghệ': 'Inverter', 'Diện tích': '10-15 m²', 'Gas': 'R32' }), image: 'https://placehold.co/400x300/e8f4fd/1a5eb8?text=Aqua+Inverter+1HP', is_featured: 1, is_sale: 1, stock: 15 },
    { name: 'Comfee Tiêu chuẩn SAP-09COS1N4 9000BTU', slug: 'comfee-sap09cos1n4-9000btu', category_id: 1, brand: 'Comfee', model: 'SAP-09COS1N4', price: 4200000, original_price: 5000000, description: 'Máy lạnh Comfee 1HP tiêu chuẩn, giá rẻ, phù hợp phòng ngủ nhỏ.', specs: JSON.stringify({ 'Công suất': '9.000 BTU', 'Công nghệ': 'Non-Inverter', 'Diện tích': '10-15 m²', 'Gas': 'R32' }), image: 'https://placehold.co/400x300/e8f4fd/1a5eb8?text=Comfee+1HP', is_featured: 0, is_sale: 1, stock: 25 },
    { name: 'Sharp Inverter AH-X9VEW 9000BTU', slug: 'sharp-ahx9vew-9000btu', category_id: 1, brand: 'Sharp', model: 'AH-X9VEW', price: 8200000, original_price: 9500000, description: 'Máy lạnh Sharp Plasmacluster kháng khuẩn, khử mùi hiệu quả.', specs: JSON.stringify({ 'Công suất': '9.000 BTU', 'Công nghệ': 'Inverter + Plasmacluster', 'Diện tích': '10-15 m²', 'Gas': 'R32' }), image: 'https://placehold.co/400x300/e8f4fd/1a5eb8?text=Sharp+9000BTU', is_featured: 0, is_sale: 0, stock: 9 },
    { name: 'Toshiba Inverter RAS-H10H2KCVG 9000BTU', slug: 'toshiba-rash10h2kcvg-9000btu', category_id: 1, brand: 'Toshiba', model: 'RAS-H10H2KCVG-V', price: 9500000, original_price: 11000000, description: 'Máy lạnh Toshiba Inverter, kháng khuẩn bạc nano, lọc không khí 4 lớp.', specs: JSON.stringify({ 'Công suất': '9.000 BTU', 'Công nghệ': 'Inverter', 'Diện tích': '10-15 m²', 'Gas': 'R32' }), image: 'https://placehold.co/400x300/e8f4fd/1a5eb8?text=Toshiba+9000BTU', is_featured: 0, is_sale: 1, stock: 7 },
    // Máy lạnh thương mại (cat 2)
    { name: 'Daikin Âm trần FCNQ15MV1 18000BTU', slug: 'daikin-fcnq15mv1-am-tran', category_id: 2, brand: 'Daikin', model: 'FCNQ15MV1', price: 32500000, original_price: 38000000, description: 'Máy lạnh âm trần Daikin 4 hướng thổi, phù hợp văn phòng, nhà hàng, khách sạn.', specs: JSON.stringify({ 'Công suất': '18.000 BTU', 'Kiểu': 'Âm trần 4 chiều', 'Diện tích': '20-40 m²', 'Gas': 'R410A' }), image: 'https://placehold.co/400x300/e8f4fd/1a5eb8?text=Daikin+Âm+Trần', is_featured: 1, is_sale: 1, stock: 4 },
    { name: 'Carrier Âm trần 42GQB012DS 12000BTU', slug: 'carrier-42gqb012ds-am-tran', category_id: 2, brand: 'Carrier', model: '42GQB012DS', price: 28000000, original_price: 32000000, description: 'Máy lạnh âm trần Carrier Inverter tiết kiệm điện.', specs: JSON.stringify({ 'Công suất': '12.000 BTU', 'Kiểu': 'Âm trần 4 chiều', 'Diện tích': '15-25 m²', 'Gas': 'R410A' }), image: 'https://placehold.co/400x300/e8f4fd/1a5eb8?text=Carrier+Âm+Trần', is_featured: 1, is_sale: 0, stock: 3 },
    // Máy giặt (cat 3)
    { name: 'LG Inverter FV1450S3W 15kg', slug: 'lg-fv1450s3w-15kg', category_id: 3, brand: 'LG', model: 'FV1450S3W', price: 17900000, original_price: 20500000, description: 'Máy giặt LG Inverter 15kg, AI DD thông minh.', specs: JSON.stringify({ 'Khối lượng': '15 kg', 'Tốc độ vắt': '1400 vòng/phút', 'Cửa': 'Cửa trước' }), image: 'https://placehold.co/400x300/e8f4fd/1a5eb8?text=LG+15kg', is_featured: 1, is_sale: 1, stock: 8 },
    { name: 'Samsung Inverter WW90T3040WW 9kg', slug: 'samsung-ww90t3040ww-9kg', category_id: 3, brand: 'Samsung', model: 'WW90T3040WW', price: 8500000, original_price: 10200000, description: 'Máy giặt Samsung EcoBubble Inverter 9kg.', specs: JSON.stringify({ 'Khối lượng': '9 kg', 'Tốc độ vắt': '1200 vòng/phút', 'Cửa': 'Cửa trước' }), image: 'https://placehold.co/400x300/e8f4fd/1a5eb8?text=Samsung+9kg', is_featured: 1, is_sale: 1, stock: 12 },
    // Máy giặt sấy (cat 4)
    { name: 'LG F2515RTGW Giặt 15kg/Sấy 8kg', slug: 'lg-f2515rtgw-giat-say', category_id: 4, brand: 'LG', model: 'F2515RTGW', price: 29900000, original_price: 35000000, description: 'Máy giặt sấy LG 15kg/8kg, TurboWash.', specs: JSON.stringify({ 'Giặt': '15 kg', 'Sấy': '8 kg', 'Tốc độ vắt': '1500 vòng/phút' }), image: 'https://placehold.co/400x300/e8f4fd/1a5eb8?text=LG+Giặt+Sấy', is_featured: 1, is_sale: 1, stock: 5 },
    // Tủ lạnh (cat 9)
    { name: 'Samsung Inverter RT38CG6000S9 380L', slug: 'samsung-rt38cg6000s9-380l', category_id: 9, brand: 'Samsung', model: 'RT38CG6000S9', price: 13800000, original_price: 16500000, description: 'Tủ lạnh Samsung 380L 2 cánh Inverter, SpaceMax.', specs: JSON.stringify({ 'Dung tích': '380 lít', 'Cửa': '2 cánh', 'Công nghệ': 'Digital Inverter' }), image: 'https://placehold.co/400x300/e8f4fd/1a5eb8?text=Samsung+380L', is_featured: 1, is_sale: 1, stock: 7 },
    { name: 'LG Inverter GN-L422GB 422L', slug: 'lg-gn-l422gb-422l', category_id: 9, brand: 'LG', model: 'GN-L422GB', price: 17500000, original_price: 20800000, description: 'Tủ lạnh LG 422L InverterLinear, DoorCooling+.', specs: JSON.stringify({ 'Dung tích': '422 lít', 'Cửa': '2 cánh', 'Công nghệ': 'InverterLinear' }), image: 'https://placehold.co/400x300/e8f4fd/1a5eb8?text=LG+422L', is_featured: 1, is_sale: 1, stock: 5 },
    // Tivi (cat 8)
    { name: 'Samsung 4K Smart TV 55AU7002 55"', slug: 'samsung-55au7002-55inch', category_id: 8, brand: 'Samsung', model: '55AU7002', price: 10990000, original_price: 13500000, description: 'Smart TV Samsung 55" 4K UHD, Crystal Processor 4K.', specs: JSON.stringify({ 'Màn hình': '55 inch', 'Độ phân giải': '4K UHD', 'OS': 'Tizen' }), image: 'https://placehold.co/400x300/e8f4fd/1a5eb8?text=Samsung+55"+4K', is_featured: 1, is_sale: 1, stock: 10 },
    // Bếp từ (cat 11)
    { name: 'Bosch Bếp từ PUE611BB5E 4 vùng', slug: 'bosch-pue611bb5e', category_id: 11, brand: 'Bosch', model: 'PUE611BB5E', price: 22000000, original_price: 26000000, description: 'Bếp từ Bosch 4 vùng nấu, kính Schott Ceran.', specs: JSON.stringify({ 'Vùng nấu': '4 vùng', 'Công suất': '7.400W' }), image: 'https://placehold.co/400x300/e8f4fd/1a5eb8?text=Bosch+Bếp+Từ', is_featured: 1, is_sale: 1, stock: 6 },
  ];

  const insertProd = db.prepare(`INSERT INTO products
    (name,slug,category_id,brand,model,price,original_price,description,specs,image,is_featured,is_sale,stock)
    VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)`);
  products.forEach(p => insertProd.run(p.name, p.slug, p.category_id, p.brand, p.model, p.price, p.original_price || null, p.description, p.specs, p.image, p.is_featured, p.is_sale, p.stock));

  // News
  const news = [
    { title: 'Chế độ ngủ đêm trên máy lạnh là gì? Có nên sử dụng không?', slug: 'che-do-ngu-dem-may-lanh', summary: 'Chế độ ngủ đêm giúp điều chỉnh nhiệt độ tự động, đảm bảo giấc ngủ thoải mái và tiết kiệm điện.', content: 'Chế độ ngủ đêm (Sleep Mode) là tính năng thông minh trên nhiều dòng máy lạnh hiện đại. Khi kích hoạt, máy lạnh tự động tăng dần nhiệt độ theo từng giờ để phù hợp với thân nhiệt cơ thể trong khi ngủ.\n\nLợi ích của chế độ Sleep Mode:\n- Tiết kiệm điện năng tiêu thụ đến 20%\n- Duy trì nhiệt độ phòng ổn định suốt đêm\n- Không gây cảm lạnh do điều chỉnh nhiệt độ tự động\n- Giảm tiếng ồn máy vận hành', image: 'https://placehold.co/800x450/e8f4fd/1a5eb8?text=Chế+Độ+Ngủ+Đêm', category: 'kinh-nghiem', created_at: '2024-06-20 09:00:00' },
    { title: 'Công nghệ Microchannel của Daikin - Giải pháp chống ăn mòn tối ưu', slug: 'cong-nghe-microchannel-daikin', summary: 'Bộ trao đổi nhiệt Microchannel của Daikin giúp chống ăn mòn hiệu quả, phù hợp khí hậu ven biển Việt Nam.', content: 'Daikin đã ứng dụng công nghệ Microchannel Heat Exchanger (MCHX) trên các dòng máy lạnh cao cấp RZF và RZFC.\n\nƯu điểm của Microchannel:\n- Tăng khả năng truyền nhiệt lên đến 40%\n- Chống ăn mòn tốt hơn nhờ lớp phủ Bluefit\n- Giảm lượng gas lạnh cần sử dụng\n- Tuổi thọ cao hơn trong điều kiện khắc nghiệt', image: 'https://placehold.co/800x450/e8f4fd/1a5eb8?text=Microchannel+Daikin', category: 'cong-nghe', created_at: '2024-06-18 08:00:00' },
    { title: 'Máy lạnh Comfee của nước nào? Có tốt không?', slug: 'may-lanh-comfee-cua-nuoc-nao', summary: 'Comfee là thương hiệu của tập đoàn Midea (Trung Quốc), hiện có mặt tại hơn 40 quốc gia.', content: 'Comfee là thương hiệu con của Tập đoàn Midea - một trong những nhà sản xuất đồ gia dụng lớn nhất thế giới.\n\nCác dòng máy lạnh Comfee nổi bật:\n- Series SAP: Inverter tiết kiệm điện\n- Series MSAG: Non-Inverter giá thành rẻ\n- Series MSAF: Tích hợp WiFi', image: 'https://placehold.co/800x450/e8f4fd/1a5eb8?text=Máy+Lạnh+Comfee', category: 'kien-thuc', created_at: '2024-04-10 10:00:00' },
    { title: '15 năm đồng hành cùng khách hàng - MK JSC tự hào chặng đường phát triển', slug: '15-nam-dong-hanh-mk-jsc', summary: 'Kỷ niệm 15 năm thành lập (2010-2025), MK JSC nhìn lại hành trình phát triển.', content: 'Năm 2025, Điện Lạnh MK JSC chính thức tròn 15 tuổi.\n\nNhững con số ấn tượng sau 15 năm:\n- Hơn 50.000 khách hàng tin tưởng\n- Trên 100.000 công trình lắp đặt thành công\n- Đội ngũ kỹ thuật viên hơn 50 người\n- Đại lý ủy quyền của 10+ thương hiệu hàng đầu', image: 'https://placehold.co/800x450/e8f4fd/1a5eb8?text=15+Năm+MK+JSC', category: 'tin-tuc', created_at: '2025-01-10 08:00:00' },
    { title: 'Hướng dẫn vệ sinh máy lạnh đúng cách tại nhà', slug: 'huong-dan-ve-sinh-may-lanh-tai-nha', summary: 'Vệ sinh máy lạnh định kỳ giúp máy hoạt động hiệu quả, tiết kiệm điện và kéo dài tuổi thọ.', content: 'Máy lạnh cần được vệ sinh định kỳ 3-6 tháng/lần.\n\nCác bước vệ sinh máy lạnh:\n1. Tắt máy và ngắt điện hoàn toàn\n2. Tháo và vệ sinh lưới lọc bụi bằng nước ấm\n3. Lau sạch phần vỏ ngoài dàn lạnh\n4. Xịt nước vệ sinh chuyên dụng lên dàn lạnh\n5. Chạy máy chế độ quạt để làm khô', image: 'https://placehold.co/800x450/e8f4fd/1a5eb8?text=Vệ+Sinh+Máy+Lạnh', category: 'kinh-nghiem', created_at: '2024-03-15 09:30:00' },
    { title: 'So sánh máy lạnh Inverter và Non-Inverter - Nên chọn loại nào?', slug: 'so-sanh-inverter-non-inverter', summary: 'Phân tích ưu nhược điểm của máy lạnh Inverter và Non-Inverter để giúp bạn lựa chọn phù hợp.', content: 'Máy lạnh Inverter:\n✅ Tiết kiệm điện hơn 30-60%\n✅ Làm lạnh nhanh và duy trì nhiệt độ ổn định\n✅ Ít ồn hơn khi vận hành\n❌ Giá cao hơn 30-50%\n\nMáy lạnh Non-Inverter:\n✅ Giá rẻ hơn\n✅ Đơn giản, dễ sửa chữa\n❌ Tốn điện hơn nhiều', image: 'https://placehold.co/800x450/e8f4fd/1a5eb8?text=Inverter+vs+Non-Inverter', category: 'kien-thuc', created_at: '2024-02-20 08:00:00' },
  ];
  const insertNews = db.prepare('INSERT INTO news (title,slug,summary,content,image,category,created_at) VALUES (?,?,?,?,?,?,?)');
  news.forEach(n => insertNews.run(n.title, n.slug, n.summary, n.content, n.image, n.category, n.created_at));

  console.log('✅ Seed data inserted successfully');
};
